# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7dbaaaf49a03000fa66063799fceb1924bf9cb3eaaf285a3b076098aad929a15d1cf2a3433d5f87f2475b9b71539d8b184828222fb78600cf0bd27348e57513

test:
  secret_key_base: e707a9e1932e4ab2c8348c07b2b90e59b96adf62430d8a97865800bb6d9bc14768d1dda8ef5b58f28595bc1222559820f5185ce0b12e4d7e5ea59b7f554cb9f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
